### PR TITLE
Filter broke get_payments on extensions

### PR DESCRIPTION
**Pull request by talvasconcelos**
added `**kwargs` to the function params

### CODE REVIEW

**Comment by dni** [comment]
where and how does it break? @jackstar12

**Comment by talvasconcelos** [comment]
> where and how does it break? @jackstar12

Here for example: https://github.com/lnbits/lndhub/blob/47ca0ac1b952dde6e4304264df1d680bd025f693/views_api.py#L121

`limit` and `offset` are not parameters of `get_payment`

**Comment by dni** [comment]
ok so we should probably, introduce a /v2/ of the api, use that in frontend, and revert the code to the original /v1/ 
@jackstar12

**Comment by jackstar12** [comment]
> ok so we should probably, introduce a /v2/ of the api, use that in frontend, and revert the code to the original /v1/ @jackstar12

I could include that in https://github.com/lnbits/lnbits/pull/1613

**Comment by arcbtc** [comment]
V2 for entire api? Sounds dramatic, surely this can be fixed without?

**Comment by callebtc** [comment]
Disagree, we should not make a new endpoint but fix the old one can keep it 100% backwards compatible. That was the goal of the Filter PR but seems like it didn't work. Lets fix it.

**Comment by callebtc** [comment]
Adding `**kwargs` to the params, doesn't change anything at all, it just makes the error go away. The bug is actually in the lndhub extension that needs to use `Filters`.

**Comment by callebtc** [comment]
Here is the issue we need to fix: https://github.com/lnbits/lndhub/issues/7

**Comment by jackstar12** [comment]
> Disagree, we should not make a new endpoint but fix the old one can keep it 100% backwards compatible. That was the goal of the Filter PR but seems like it didn't work. Lets fix it.

@callebtc 100% backwords compatibility wont really be possible for https://github.com/lnbits/lnbits/pull/1613 because it changes the response model so I think keeping the new stuff on a seperate endpoint for now should be the easisest and safest (there might be more stuff that depends on the current api). At some point the old one can be removed / deprecated

**Comment by arcbtc** [comment]
A vote for new api endpoint, then when people complain we point to the pagination endpoint

**Comment by callebtc** [comment]
> A vote for new api endpoint, then when people complain we point to the pagination endpoint

Agreed, I assumed the response remains the same. The endpoint should either not change or be 100% backwards compatible. So let's do a separate endpoint for paginated payments and restore the functionality of the old endpoint to exactly the same as it was before.

**Pull request closed without merging**
