### PR TITLE
use floor() instead of round() to convert msat to sat in frontend

### PR DESCRIPTION
**Pull request by prusnak**
I haven't tested this yet, but this hopefully fixes https://github.com/lnbits/lnbits/issues/2031

### CODE REVIEW

**Comment by dni** [comment]
screenshot-1698410051

not working for me, subsat value `950` but still showing 1 sat on the balance, i stepped through with the debugger, and it seems the activeBalance value passed is 0. i dont really have a clue where the 1 comes in.

**Comment by motorina0** [comment]
tACK

- api call:
  - image


- UI on this branch:
  - image
- UI on dev branch:
  -  image

**Review by motorina0 — APPROVED** [review]

**Comment by prusnak** [comment]
@motorina0 any idea why this works for you and not for @dni ?

@dni maybe you used the cashed version of the javascript and you didn't test the new code?

**Comment by prusnak** [comment]
Rebased on top of current dev and force pushed.

**Comment by motorina0** [comment]
> @motorina0 any idea why this works for you and not for @dni ?

I only had one issue while testing: in `Manage Server` > `Theme` the currency was set to `sat` instead of `sats` (from previous tests) and the formatting in the front end was different.

image


For the `millisats` value I have simply changed the value in my local DB:
```sql
update apipayments set amount = 1750 where checking_id = '...'
```

Note: 
- a value of `1750` (/1000) will been rounded to `2`.
- a value of `1050` (/1000) will been rounded to `1`, not to `2`.

**Comment by dni** [comment]
the issue was, that 750 millisats should be rounded to 0

**Comment by dni** [comment]
same. 
screenshot-1699252009

**Comment by dni** [comment]
ok, i figured it out, it wasnt actually coming from the `/wallet` api call, it somewhere set in the `this.g.wallet`, i dont even know where it comes from, it seems extremely complicated for me how the wallet info is fetched. 

but after setting the milisats in the db, it works. thanks @motorina0

**Review by dni — APPROVED** [review]

**Pull request merged**
