### PR TITLE
chore: update to Vue 3

### PR DESCRIPTION
**Pull request by dni**
wip

### CODE REVIEW

**Comment by motorina0** [comment]
@dni what can be done to finish this PR?

**Comment by dni** [comment]
as far as i remember the issue is extension need to change. so i guess this could be a goal for `0.13.0` where we prepare ext updates upfront.

**Comment by bitkarrot** [comment]
@dni I realize the vue3 conversion has been going on for a while, but I am curious to know if its OK to make new extensions with Vue3?

**Comment by dni** [comment]
> @dni I realize the vue3 conversion has been going on for a while, but I am curious to know if its OK to make new extensions with Vue3?

sits szadly incompatible

**Comment by bitkarrot** [comment]
oh dear...does that mean we are stuck on vue2 forever or does it mean eventually all extensions have to be rewritten to support vue3?

**Comment by dni** [comment]
> oh dear...does that mean we are stuck on vue2 forever or does it mean eventually all extensions have to be rewritten to support vue3?

eventually :) but it does not have a lot of prior now, maybe 0.14.0

**Comment by prusnak** [comment]
superseded by https://github.com/lnbits/lnbits/pull/2677

**Pull request closed without merging**
