### PR TITLE
feat: add libwally for liquid support

### PR DESCRIPTION
**Pull request by dni**
this is needed for liquid support in the new boltz extension, sadly i could not get it to work with embit library, liquid support is not quite ready there and no documentation or tests available

### CODE REVIEW

**Comment by prusnak** [comment]
I think we should start using optional group dependencies for the project.
Especially when we are introducing binary dependencies. Same goes for https://github.com/lnbits/lnbits/pull/1897

That is, add this dependency using `poetry add wallycore --group=liquid` and then requiring user to install via `poetry install -E liquid` instead of just `poetry install`.

Also boltz should import wallycore conditionally, so everything works just fine (modulo liquid support) when wallycore is not installed.

What do you think, @dni?

**Comment by motorina0** [comment]
> We then require user to install via `poetry install -E liquid` instead of just `poetry install`. Or is this too much to ask from admins?

I think this is a very good solution.
If the admin are planning to run the `blotz` extension then they are technical enough to use the `-E` flag.

**Comment by prusnak** [comment]
I pushed the poetry extra change to commit 30137d596d520a26f7551def271a7290cfd0bbef

**Comment by dni** [comment]
if we want to do this, i think we should do that for the other dependencies aswell.

**Review by prusnak — APPROVED** [review]

**Review by motorina0 — APPROVED** [review]

**Pull request merged**
