### PR TITLE
chore: remove lnurl wallet and withdraw feature

### PR DESCRIPTION
**Pull request by dni**
i think this feature is undocumented and the code is very outdated. i don't think it is worth to keep.

looking at the `/lnurlwallet` endpoint for example, it creates a new user and wallet without even checking if the creation of users is allowed.

WIP just did this to see how much code is related to this features

### CODE REVIEW

**Comment by arcbtc** [comment]
nack
This is a really useful feature used by atms, and faucets

**Comment by prusnak** [comment]
> This is a really useful feature used by atms, and faucets

Shouldn't they use LNURL-w extension for that?

**Comment by arcbtc** [comment]
Actually this might not be what I am thinking of, is it the auto wallet create thingmabob?

**Comment by arcbtc** [comment]
> > This is a really useful feature used by atms, and faucets
> 
> Shouldn't they use LNURL-w extension for that?

I thought this was the auto-wallet builder endpoint, my mistake

**Comment by arcbtc** [comment]
No it is that endpoint!
Thiis is useful, you can add an lnurl prefix so if scanned and opened in browser it will creata a wallet and fund it with the lnurl

**Comment by dni** [comment]
screenshot-1711462299

**Comment by prusnak** [comment]
Jmeter CI job is failing

**Review by arcbtc — APPROVED** [review]

**Review by talvasconcelos — APPROVED** [review]

**Pull request merged**
