### PR TITLE
feat: remove bundle

### PR DESCRIPTION
**Pull request by dni**
breaking change in how to install lnbits
you will need to run `make build` instead of `poetry install` and it required to install nodejs for building
after an update you now should also run `make build`

### CODE REVIEW

**Comment by arcbtc** [comment]
So make will bundle?

**Comment by dni** [comment]
yep that was the idea

**Comment by arcbtc** [comment]
Will this impact nix @prusnak ?

**Comment by dni** [comment]
decided its not worth it to force the user to have npm installed

**Pull request closed without merging**
