### PR TITLE
README improvements

### PR DESCRIPTION
**Pull request by dennisreimann**
Working in some things I noticed while setting up the project locally.

### CODE REVIEW

**Comment by eillarra** [comment]
Maybe is a good moment to see what needs to be removed from the README. Ideally, dev docs (how to set up a dev environment, info about different wallets) should go in the `docs/` folder.

We can leave the README for a general overview and then point to the actual docs from there.

Docs are using GitHub pages and are hosted on <https://lnbits.org>

**Comment by eillarra** [comment]
Looks good to me. Can you maybe squash the different commits?

**Comment by dennisreimann** [comment]
Ok, here's a all-in-one version :)

**Comment by eillarra** [comment]
Thanks, I hope everything went well, because I was just merging it :)

**Pull request merged**
