### PR TITLE
FEAT: add localisation to lnbits frontend

### PR DESCRIPTION
**Pull request by dni**
localisation for frontend

* adds vue-i18n

it is still incomplete translation, but it could be a good starter to engage new contributors.

### CODE REVIEW

**Comment by motorina0** [comment]
tACK

It would be nice for each language to have its own file (as the number of languages increases, it will be easier to manage)

**Comment by motorina0** [comment]
Some missing translations:
- image

- image

**Comment by arcbtc** [comment]
> tACK
> 
> It would be nice for each language to have its own file (as the number of languages increases, it will be easier to manage)

What's state of play on this? Would be good to get merged

**Comment by dni** [comment]
split i18n.js into seperate languages

**Comment by arcbtc** [comment]
Will this work for extensions, can they have there own language files?

**Review by motorina0 — APPROVED** [review]
LGTM
Approved

**Review by arcbtc — APPROVED** [review]
Looks good LFG!

**Pull request merged**
