### PR TITLE
Swap Alby logos

### PR DESCRIPTION
**Pull request by stackingsaunter**
Swaps logos for better version of monochromatic Alby logos

### CODE REVIEW

**Comment by prusnak** [comment]
Originals were 200px x 90 px, the new ones are 210px x 91px.

Please make sure you resize/crop them to the correct dimensions.

Also run `optipng -o 7 alby*.png` before submitting them.

**Review by prusnak — CHANGES_REQUESTED** [review]
Originals were 200px x 90 px, the new ones are 210px x 91px.

Please make sure you resize/crop them to 200 px x 90 px.

Also run `optipng -o 7 alby*.png` before submitting them.

**Review by prusnak — CHANGES_REQUESTED** [review]
The dimensions of new images are not changed to 200px x 90px like requested.

**Comment by stackingsaunter** [comment]
My bad, I misunderstood you, fixing now

**Review by prusnak — APPROVED** [review]
Thanks, approved!

**Review by dni — APPROVED** [review]

**Pull request merged**
