### PR TITLE
Extension: Tip Jar

### PR DESCRIPTION
**Pull request by Fittiboy**
This extension implements a tip jar for a nice donation flow.
It's essentially a stripped-down version of my Stream Alerts extension, to provide the same payment flow, dispatching to any arbitrary webhook.
So it's essentially this:
 - Donation page, with "Name," "Amount," and "Message" fields
 - Lightning _and_ on-chain support via SatsPay charges
 - Arbitrary webhook to send to

This provides a clean one-stop shop for all Bitcoin donations. I personally want this for my bitcoindevlist.com donation link, so I'll build it either way. Just wanted to offer it as an extension as well if that's cool! :+1:

(As you can see, it's currently mostly just cloned Stream Alerts code with barely any modifications. I'll work on it in a bit)

### CODE REVIEW

**Comment by arcbtc** [comment]
Sounds good. For the LNbits TipJar we use the Paywall extension, which works well, but a dedicated tipjar using the satspayserver sounds very worthwhile

**Comment by Fittiboy** [comment]
I finally got around to implementing everything. Been playing around with it for a bit and it seems to be working quite well.

**Comment by arcbtc** [comment]
Nice. Congrats dude! Looking forward to using for the official lnbits tipjar

**Comment by Fittiboy** [comment]
I've been running this for a bit now, and have done two cosmetic changes. Functionally, it's ready to merge.
@arcbtc is there anything you want changed before merging?

**Pull request merged**
