### PR TITLE
enable nix flake on {aarch64,x86_64}-darwin

### PR DESCRIPTION
**Pull request by prusnak**

### CODE REVIEW

**Comment by callebtc** [comment]
LGTM, can't test though!

**Comment by prusnak** [comment]
> LGTM, can't test though!

Currently, the nix build is broken anyway because of https://github.com/lnbits/lnbits/issues/1088 and I was not able to figure it out why so far. ...

**Comment by arcbtc** [comment]
Hi @prusnak! Its an honour to have you here 🙌.
Currently we are working to Poetry while we work on some big updates, such as pulling out extensions from core https://github.com/lnbits/lnbits/pull/1231
We will get lnbits core audited (hopefully you can help us organise that?). Once audited we will look to get our nix install working again, then I suggest having nix as our development standard.

**Comment by arcbtc** [comment]
This is all in the near future btw. @motorina0 PR should be merged over the next few weeks 👍

**Pull request merged**
