### PR TITLE
Updated new wallet warning modal text to clarify importance of backing up login creds

### PR DESCRIPTION
**Pull request by blackcoffeexbt**

### CODE REVIEW

**Review by motorina0 — APPROVED** [review]
LGTM

**Review by dni — DISMISSED** [review]
ci failing

**Comment by motorina0** [comment]
> ci failing

fixed

**Review by talvasconcelos — APPROVED** [review]

**Comment by DoktorShift** [comment]
i had regarding to that wonderfull pr vom BC the thought to force push the new user to "my account" section. Disable the "I understand" button or do not display it. So new user have to go to "my Account" otherwise the add will not disapear.

It would be a tradeoff security vs. comfort

**Pull request merged**
