### PR TITLE
Configure invoice expiry from ENV variable

### PR DESCRIPTION
**Pull request by cryptoteun**
PR makes the invoice expiry configurable. Is also a fix for #352 

Please review carefully:

- I'm not a DEV so not sure if I followed coding standards/best practices
- Tested on CLN, that worked well. 
- But not tested on a LND instance.

### CODE REVIEW

**Comment by dni** [comment]
cool, i started a branch last week, where i make expiry also configurable, on a invoice to invoice basis. ENV variable is nice, but i think the ability to define your timeout on each invoice, would be very awesome also.

**Comment by cryptoteun** [comment]
> 

Yeah, that's why I made this one only for lnd and cln. But I have to check tonight why the build is failing.
It worked local so perhaps it's something with setting the ENV for the regtest. @callebtc, any idea?

**Comment by dni** [comment]
it failing becuase it cant get the env variable, i guess for regtest a custom one is used where your variable is missing?

**Comment by callebtc** [comment]
Thank you, very useful PR. I'd like to tackle this one with you. 

Currently working on an updated payment interface for LND wallets so that will have to be rebased to PR #745 at some point.

**Comment by dni** [comment]
ok, i guess, this one has to be changed if we decide to use a env variable. https://github.com/lnbits/lnbits-legend/blob/main/.github/workflows/regtest.yml

**Comment by callebtc** [comment]
Concept ACK but the way it is solved here is suboptimal (see my comment above). 

I reckon that it would be better to pass the desired expiry to the wallet init in `settings.py`.

We also would need to add tests for this PR.

**Comment by cryptoteun** [comment]
Spoke about it with Calle, but don't know how to resolve correctly. Calle will look into it

**Pull request closed without merging**
