### PR TITLE
migrate from flask to quart.

### PR DESCRIPTION
**Pull request by fiatjaf**
Closes https://github.com/lnbits/lnbits/issues/80.

### CODE REVIEW

**Comment by arcbtc** [comment]
Getting white screen of death on extensions :(
image

**Comment by fiatjaf** [comment]
You didn't need to delete any dbs, but there were other dependencies involved: `pipenv sync` is the command to be run when you just want to get your local environment synced with some commit.

**Comment by arcbtc** [comment]
Still getting a white screen when clicking extensions
Pulled -> ```pipenv sync``` ->  ```pipenv run python -m lnbits```

**Comment by fiatjaf** [comment]
I'll go ahead and merge this because everything seems to be fine and I want to click the merge button.

The mypy check is failing but it shouldn't. it runs fine on my machine with all the exact same versions, so I'm trying to debug that but it's weird.

**Pull request merged**
