### PR TITLE
TEST: Monster pyright PR, fixing core, breaking everything

### PR DESCRIPTION
**Pull request by dni**
TEST: Monster pyright PR, fixing core, breaking everything

- monster pyright pr
- add workflow

### CODE REVIEW

**Comment by prusnak** [comment]
I think it's better not to use the pyright python wrapper (which is not official) but just install pyright and run it via `npx pyright`

**Comment by prusnak** [comment]
> I think it's better not to use the pyright python wrapper (which is not official) but just install pyright via `package.json` (same as prettier) and run it via `./node_modules/.bin/pyright` (again, same as prettier)

I implented this in https://github.com/lnbits/lnbits/pull/1367 - my idea is to merge this first and then you can rebase your PR on top of that (+ you can drop the python pyright package completely)

**Comment by prusnak** [comment]
> I implented this in #1367 - my idea is to merge that PR first and then you can apply your PR on top of that:

#1367 has been merged

**Comment by prusnak** [comment]
Maybe let's wait until https://github.com/lnbits/lnbits/pull/1369 is merged before rebasing this PR

**Comment by dni** [comment]
ready for rebase? should i do it?

**Comment by prusnak** [comment]
https://github.com/lnbits/lnbits/pull/1369 has been merged, so you can now rebase this on top of main

**Pull request closed without merging**
