### PR TITLE
fix flake error: #1088

### PR DESCRIPTION
**Pull request by dni**
fixes flake install issue thanks to https://github.com/lnbits/lnbits/issues/1088

### CODE REVIEW

**Comment by afilini** [comment]
That's not enough to fix the build, in my tests I also had to override some packages due to the setuptools "bug" (see https://github.com/nix-community/poetry2nix/blob/master/docs/edgecases.md).

But after fixing those, the latest 0.10.2 cannot inherently work with nix, it tries to download the extensions in the folder of the source code, which is in the /nix/store and it's read only. So even if you get it to build it won't run.

I tried hacking something together to store the extensions in a different writable directory (like `/var/lib/lnbits/extensions`) but for some reason even when setting the `PYTHONPATH` lnbits would not pick them up, so I ultimately gave up.

I think in order to make this work the first step would be to add an option to install extensions in a separate path and load them from there, then it can be made to work with nix. I personally don't have time to work on it at the moment.

**Comment by prusnak** [comment]
> I also had to override some packages due to the setuptools "bug"

Sent PR to poetry2nix here: https://github.com/nix-community/poetry2nix/pull/1046

**Comment by afilini** [comment]
I switched back to an older version of lnbits, this is what I have:

```
embit = super.embit.overridePythonAttrs (old: {
  buildInputs = old.buildInputs or [ ] ++ (with pkgs.python39.pkgs; [ setuptools ]);
});
pylightning = super.pylightning.overridePythonAttrs (old: {
  buildInputs = old.buildInputs or [ ] ++ (with pkgs.python39.pkgs; [ setuptools ]);
});
represent = super.represent.overridePythonAttrs (old: {
  buildInputs = old.buildInputs or [ ] ++ (with pkgs.python39.pkgs; [ setuptools ]);
});
lnurl = super.lnurl.overridePythonAttrs (old: {
  buildInputs = old.buildInputs or [ ] ++ (with pkgs.python39.pkgs; [ setuptools ]);
});
sqlalchemy-aio = super.sqlalchemy-aio.overridePythonAttrs (old: {
  buildInputs = old.buildInputs or [ ] ++ (with pkgs.python39.pkgs; [ setuptools ]);
});
sse-starlette = super.sse-starlette.overridePythonAttrs (old: {
  buildInputs = old.buildInputs or [ ] ++ (with pkgs.python39.pkgs; [ setuptools ]);
});
```

**Comment by prusnak** [comment]
> I switched back to an older version of lnbits, this is what I have:

Thanks, created PR out of these too: https://github.com/nix-community/poetry2nix/pull/1049

**Review by prusnak — APPROVED** [review]
I think we should merge this.

I have couple of other fixes in my pipeline, but they are waiting for external PRs to be merged, so let's not block this change and I'll send another PR when I am ready.

**Pull request merged**
