### PR TITLE
add UUID as id instead of sequential integer

### LINKED ISSUE #1230: [Feature request] LNURLp links should have a random ID, not sequential
**Problem**
LNURLp links look like this right now: https://legend.lnbits.com/lnurlp/**123456** and the number goes up with every new link. 

**Solution**
Use a UUID instead of a counter.

### PR DESCRIPTION
**Pull request by talvasconcelos**
Fixes #1230

### CODE REVIEW

**Comment by callebtc** [comment]
ACK

**Comment by callebtc** [comment]
LGTM

**Review by callebtc — APPROVED** [review]

**Comment by arcbtc** [comment]
Wait, what, this is not a bug, did someone complain? https://github.com/lnbits/lnbits/issues/1230#issuecomment-1367605687

**Comment by fiatjaf** [comment]
Looks good to me, but I think https://hashids.org/ would be a nicer solution here, the ids would be shorter, it is a much less disruptive change since there are no migrations, and also it would apply retroactively to all existing ids (although this may be an anti-feature).

Yeah, I don't know, maybe proceed with this change, the UUIDs are not that big.

**Comment by arcbtc** [comment]
Aright, if you're happy 👍
LGTM

**Pull request merged**
