### PR TITLE
Update phoenixd.py

### PR DESCRIPTION
**Pull request by Hodladi**
Fix for the description_hash with phoneixd server

### CODE REVIEW

**Comment by prusnak** [comment]
Please keep the todo comments - you have not addressed them, so you should not remove them

**Comment by Bashy** [comment]
Was it tested? I might have time to test this weekend, and maybe provide a PR if this ones is not ok, but I think this is **not** going to work since
```py
            data: Dict = {
                "amountSat": f"{msats_amount}",
                "description": memo,
                "externalId": "",
            }
```
`description` here - as I understand - should not has `memo`, but rather the expected `description_hash`, so we should have something like

```py
            data: Dict = {
                "amountSat": f"{msats_amount}",
                "description": description_hash,
                "externalId": "",
            }
```

Here https://github.com/ACINQ/phoenixd/pull/50/files#diff-154655ec623b797aed456fbb139aba5ea257320178b9574f12f676560f3c3b4c, you can see line -154/+162 that `description` expects the `description_hash`

`memo` is not relevant for phoenixd

**Comment by Bashy** [comment]
To clarify my previous comment, it might work but not the expected way where phoenixd actually processes the `description_hash`

**Comment by Hodladi** [comment]
It works, I'm running my LNBits instance with that change and it works perfectly.

I'm no python dev so this is probably possible to do better but as I said, it do work.

**Comment by Funman2** [comment]
this branch is able to even receive nostr zaps, whereas in  #2514 they don't go through.

**Comment by prusnak** [comment]
Closed in favor of https://github.com/lnbits/lnbits/pull/2514

**Pull request closed without merging**
