### PR TITLE
Invoice creation UI: Replace input mask with pattern and inputmode

### PR DESCRIPTION
**Pull request by blackcoffeexbt**
Replacing the input masks with pattern and inputmode has a number of benefits:

+ On mobile, the keyboard shows only numbers (See iamge below)
+ Allows additional specification for currencies that need more 2 decimal places (e.g. Chile, Libya) - http://www.londonfx.co.uk/ccylist.html
+ Improves the UX of entering an invoice amount on mobile. The previous reverse input mask was a bit of a mind bender.

image

### CODE REVIEW

**Comment by motorina0** [comment]
Why was `package-lock.json` updated?

**Review by motorina0 — APPROVED** [review]

**Comment by blackcoffeexbt** [comment]
> Why was `package-lock.json` updated?

idk, will check and revert. I think it's a node version issue on my side.

**Comment by prusnak** [comment]
also change in `lnbits/static/bundle.min.js` should be reverted

**Review by prusnak — CHANGES_REQUESTED** [review]
also the change in `lnbits/static/bundle.min.js` should be reverted

please run `make check` before commiting changes next time

**Review by prusnak — APPROVED** [review]

**Review by dni — APPROVED** [review]

**Pull request merged**
