### PR TITLE
Multilanguage intensifies

### PR DESCRIPTION
**Pull request by arbadacarbaYK**
Minor format change that lead to errors before just in case

Dutch and Pirate Slang added 👀☠️😂
Used PI because there is no country-code PI

### CODE REVIEW

**Comment by dni** [comment]
omg, i love the pirate one :D

**Comment by callebtc** [comment]
`make format` please :)

**Review by callebtc — APPROVED** [review]

**Comment by dni** [comment]
ill take this one and merge fr, de, pi

**Comment by arbadacarbaYK** [comment]
> `make format` please :)

tellme how for the future and Ill do it :/

**Comment by dni** [comment]
added this PR to https://github.com/lnbits/lnbits/pull/1675

**Pull request closed without merging**
