### PR TITLE
[FEAT]: nix app installer

### PR DESCRIPTION
**Pull request by arcbtc**
### Summary
- This PR handles the UI/UX of installing NIX modules from the LNbits Admin Console.
- The integration with the NIX process is not in scope of this PR.
- The NIX package definition lives here: https://github.com/lnbits/nix-lnbits/blob/main/nix-packages.json
- The UI is generated based on the fields in the `.nix` files.
- When the values are updated on the UI then a file will be created/update on `lnbits_data_folder/nix/config/{package.id}.json`
- Subsequently the values in this file will be loaded each time the configurations are edited

### TODO (not in this PR)
 - add environment variable (and UI) for nix packages (similar to `lnbits_extensions_manifests`)
 - convert the normalised JSON configs (from `lnbits_data_folder/nix/config/{package.id}.json`) to valid `.nix` config files
 - implement the functionality for the `Add` button (call a `nix` script to install that package)
 - allow uninstall/update of packages

### Screen-share

https://github.com/lnbits/lnbits/assets/2951406/fdcfdd75-8eeb-4372-a84a-2b035edf66a7

### CODE REVIEW

**Comment by arcbtc** [comment]
Its so beautiful!

Wouldnt building the nix config from the jsons remove/uninstall packages, as they would no longer be included.

We will also need "Open" button for some applications with a frontend.

**Comment by bitkarrot** [comment]
Wow! Taking it to the next level! Can't wait.

**Comment by motorina0** [comment]
@arcbtc what do we do with this PR?

**Comment by arcbtc** [comment]
This is a

**Pull request closed without merging**
