### PR TITLE
WIP: Jitsi extension

### PR DESCRIPTION
**Pull request by nochiel**
This PR implements the features requested in lnbits/lnbits/issues/211. 

*An extension that creates a Jitsi chat bot which allows participants to send funds back/forth in a Jitsi meeting.*

- This initial implementation is as simple as possible: we use the [Jitsi iFrame API](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe) to create a chat bot that allows payments to be made by participants in the meeting. The entire UX is via chat commands. This also means that we cannot modify the video conferencing UI that participants use in any way. When participants are invited to the meeting, the UI they see is the standard Jitsi UI.

- The more sophisticated implementation (which would require a lot more work than the chat bot) would be to create a custom UX that uses either the [Jitsi low-level lib-jitsi-meet api](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ljm-api) or [Jitsi Web SDK](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-web-sdk) for video conferencing functionality. This would be a bespoke LNBits video conferencing app. Invited participants would then go directly to the LNBits Jitsi app instead of using a standard invite page hosted by Jitsi. With a custom LNBits video conferencing app we could then implement any fancy UX we want e.g. overlaying LNUrl QRs on participants' thumbnails. If a custom LNBits video conferencing app is desired, it can be worked on as a separate PR.

## TODO: Chat Bot

- [x] Allow host to configure the room name. (right now it's hardcoded for testing).
    - [ ] Handle changes to the room name or configuration during a conference call. 
- [x] Each participant given their own LNBits wallet.
    - [ ] Handle changes to the participant's nickname or other details during a conference call.
- [ ] Provide a chatbot with an interface like [LightningTipBot](https://github.com/LightningTipBot/LightningTipBot). We want the following commands:
    - [x] `/help`
    - [x] `/balance`
    - [x] `/pay`
        - [x] Payments can be done from an external wallet [scan qr code from phone wallet]
            - [x] Show the participant a lightning invoice.
            - [-] Show the participant a QR code.
                - Displaying QR codes isn't possible because the Jitsi API doesn't allow us to display images in chat or overlayed on video.
            - [ ] Show recipient a notification when they receive a payment made using an invoice paid with an external wallet.
        - Payments can be done with an LNBits wallet 
            - [x] If the participant has a balance in their LNBits wallet, use it to pay the other participant instead of showing an invoice.
         - [x] Show participant a notification when they receive a payment.
         - [ ] When a participant joins a meeting, show them the URL to their LNBits wallet.
         - [ ] Streaming sats: payments per minute while the participant is in the meeting.
            - [ ] Only while speaking.
            - [ ] Continuously, until payments are stopped.
            - [ ] Boost active payments by an amount.

    - [x] `/deposit`
        - [ ] Notify the participant when a deposit has succeeded (been received by LNBits).

    - [ ] `/wallet`: Sets the participants wallet to an LNBits wallet specified in a URL.
        - This allows the participant to use an LNBits wallet they already have.

- [x] Port to FastAPI branch.

## TODO: LNBits Jitsi App

- [ ] WIP: Prototype UI using jitsi web sdk.

---

- [ ] Port to lnbits/LNbits-Infinity.

## @maxhillebrand's [feature list](https://github.com/lnbits/lnbits-legend/issues/211#issuecomment-859901793)

- [x] Every jitsi call participant can get paid.
- [x] Every jitsi call participant can pay others.
- [-] Listeners of a livestream of the jitsi call can pay participants via scanning QR code. (Requires custom UI.)
- [ ] Payments per minute with a custom sat amount, either only when the participant is speaking, or even when he is silent.
    - [ ] One-time boost payments with a custom sat amount.
- [ ] Optionally a payment required to join the call as participant. This could even be split up, so that X% of the sent amount go directly to the organizer of the event as an upfront fee, while Y% are deposited into the participants lnbits wallet, for future payments in the call.
- [x] At the end of the call, participants can withdrawl their sats to a different wallet, maybe they can stay in a long term lnbits wallet.
- [ ] One potential problem that I see, is that jitsi participants are ephemeral and without long lived reputation. What will happen if a participant refreshes his browser, and appears as a new participant? He should still have the same lnbits wallet etc.
- [x] Hopefully all of this can be done without changing jitsi code, or without requiring a self-hosted jitsi setup. It would be awesome if this can be done with ANY public jitsi server, or maybe even other call applications too!

## Bugs

- [ ] If the host (chatbot) refreshes the page and rejoins the chat, all the previous commands will be re-run. **This is bad**. Jitsi's chat doesn't give us timestamps for each message so we have to implement our own logging in such a way that we only process commands that have not been processed before.
- [x] FIXED: When a participant is paid, the `/balance` command doesn't immediately show the updated balance. (The wallet is refreshed if the user manually browses to their LNbits wallet page.)
- ~[ ] The chatbot doesn't process it's own commands e.g. if the host types commands into the chat.~
- [ ] Nicknames used by participants are not canonical. If 2 participants have the same nickname there's no way to uniquely identify them. Create cannonical names when participants join.
- [ ] Nicknames used by participants have to be one word without spaces otherwise the chatbot won't parse the `/pay` command correctly.

---

If you'd like to donate some sats so I can add more features and bug fixes to this extension, feel free to use L1 or the [lightning addresses](https://lightningaddress.com) below:
- `bc1qrajmrqf5lq2yv0nmaa5n544cjhgzlyed7s6p0xfslqmgf0n6ykps92qumq`
- <nick0o0o@ln.tips> 
- <nick0o0o@lntxbot.com>

### CODE REVIEW

**Comment by fiatjaf** [comment]
Wow.

**Comment by MaxHillebrand** [comment]
That's pretty awesome @nochiel, thanks a lot for tackling the feature!

**Comment by arcbtc** [comment]
Holy smokes I've wanted this to exist forever!
So can I share a jitsi link, and as host, make provide a cam-girl service?

**Comment by nochiel** [comment]
> **Important:** Make sure You develop this for the FastAPI branch, as we're switching very soon.

Will do, @arcbtc . Thanks for the heads-up.

> So can I share a jitsi link, and as host, provide a cam-girl service, all I need is[ jitsi and lnbits?

Yes!  That will be work. I'll have something you can test in a few days.

Initially we'll have to use the Chatbot, but Jitsi has libraries that allow us to create custom UIs so, hopefully, those libraries are flexible enough to allow us to develop a fully integrated UI. (The custom UI will require significantly more work and testing but as far as I can tell, all the features you and @MaxHillebrand  discussed are possible.

**Comment by arcbtc** [comment]
Hows this coming along, any help needed for switching what you have to FastAPI?

**Comment by nochiel** [comment]
> Hows this coming along, any help needed for switching what you have to FastAPI?

😄 I've been afk for the holiday for the past week and a half but I'll be back at it later this week. The FastAPI work looks straightforward. I'll definitely ping you when I need help. Thanks again and happy holidays!

**Comment by nochiel** [comment]
@MaxHillebrand @arcbtc The chatbot works for basic functionality. If you'd like to test it I'd be grateful for the feedback.

**Comment by MaxHillebrand** [comment]
I don't have a lnbits PR testing setup yet - would you mind sending some screenshots please?

**Comment by nochiel** [comment]
> I don't have a lnbits PR testing setup yet - would you mind sending some screenshots please?

Will do.

**Comment by arcbtc** [comment]
Yo. Sorry I overlooked this. Very cool. I couldnt get the bot to fire though 
image

**Comment by MaxHillebrand** [comment]
that's awesome progress! Thanks
any plans for recurring payments? Especially those conditional ones, like only pay to the person who's speaking.

**Comment by nochiel** [comment]
> Yo. Sorry I overlooked this. Very cool. I couldnt get the bot to fire though 

Thanks for testing. You have to invite a new participant to the Jitsi meeting. Currently, the LNBits administrator can't control the chatbot. (Due to a quirk in how Jitsi's API works.)

So: invite 2 new test participants and access the bot through their chats. That should work.

**Comment by nochiel** [comment]
> that's awesome progress! Thanks any plans for recurring payments? Especially those conditional ones, like only pay to the person who's speaking.

Yes. I'm working on that.

I've been trying to figure out if we can do better than a chatbot, that is, have a proper LNBits meeting app that uses Jitsi, and that would give us a lot more flexibility to add/customise features. Hopefully I'll make some progress in that regard.

**Comment by nochiel** [comment]
> I've been trying to figure out if we can do better than a chatbot, that is, have a proper LNBits meeting app that uses Jitsi, and that would give us a lot more flexibility to add/customise features. Hopefully I'll make some progress in that regard.

I've been looking into this and experimenting with [lib-jitsi-meet](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ljm-api). I'm now not confident that it's worthwhile to create a bespoke Jitsi client because the increased flexibility I was hoping for comes at the cost of disproportionately increasing the size of the codebase. Essentially, we'd be recreating the web UI that Jitsi have already implemented.

So, @arcbtc and @MaxHillebrand, should I go ahead and finish work on the chatbot as described in the PR? Will that be suitable for your needs?

**Comment by nochiel** [comment]
> @MaxHillebrand : can we fork some parts of the existing web UI and put this ontop of lib-jitsi-meet?

I'll look into this.

**Comment by nochiel** [comment]
> can we fork some parts of the existing web UI and put this ontop of lib-jitsi-meet?

I'll block in some time do that next month because it's a substantial amount of work. That is, making a new video conferencing app that uses Jitsi.

> can we add some GUI to the chatbot, maybe in form of buttons that the user can click? Telegram bots can do that.

Unfortunately, Jitsi doesn't have this functionality.

**Comment by callebtc** [comment]
Bump! Is this extension still alive? :) Please merge main into this (or rebase) since a lot has happened since the last activity.

**Comment by nochiel** [comment]
On Wed, 3 Aug 2022 at 15:59, calle ***@***.***> wrote:

> Bump! Is this extension still alive? :) Please merge main into this (or
> rebase) since a lot has happened since the last activity.
>
Thanks. Yes, this is still alive. There still a bit of work I have planned
for it to improve UX, reliability, and to add features.

**Comment by nochiel** [comment]
> can we fork some parts of the existing web UI and put this ontop of lib-jitsi-meet?

@MaxHillebrand I've forked the Jitsi web UI and added a bunch of functionality to it. It will be possible afaict to add whatever functionality we want going forward with a nice UX instead of a chatbot. (I've been busy the past couple of months but now that I have a bit more time I'm optimistic that I'll have something for you to test soon.)

**Comment by arcbtc** [comment]
Bump. I want this extension to exist so bad. Rather than have a UI, we can have a simpler version for now, roll out, then update later. A simple version is better than now version.

**Comment by nochiel** [comment]
> Bump. I want this extension to exist so bad. Rather than have a UI, we can have a simpler version for now, roll out, then update later. A simple version is better than now version.

Thanks for the nudge @arcbtc. And sorry for the delay. 

I've just wound up most of my other blocking commitments and will be working in this over this holiday because I'll have a lot more time to myself. You can expect some updates because I too need the functionality!

**Comment by dni** [comment]
this extension should be its own repo @nochiel :)

**Comment by dni** [comment]
we should move this PR to its own repo aswell! 
are you still up for its? you than could more independently work on it!

i can help you setup the repository on lnbits organisation if you wish, or do your own :)

**Comment by nochiel** [comment]
> we should move this PR to its own repo aswell! are you still up for its? you than could more independently work on it!
> 
> i can help you setup the repository on lnbits organisation if you wish, or do your own :)

This sounds good. I'll block in some time this week to set up the repository and clean up the work on the forked client. (Right now it's a bit of a mess which is why I haven't pushed it.)

Then, by about 2022-04-29, I'll transfer the repository to the lnbits organization. Does that sound reasonable?

**Comment by dni** [comment]
i create it push the code there and make you contributor

**Comment by dni** [comment]
https://github.com/lnbits/jitsi

**Comment by dni** [comment]
https://github.com/lnbits/jitsi/issues/1

**Comment by nochiel** [comment]
> i create it push the code there and make you contributor

Aha. Thank you! Much appreciated.

**Pull request closed without merging**
