### PR TITLE
feat: improve on extension page layout

### PR DESCRIPTION
**Pull request by dni**
simplified and improved responsiveness

screenshot-1718971749
screenshot-1718971302
screenshot-1718971295
screenshot-1718971288

### CODE REVIEW

**Review by motorina0 — APPROVED** [review]
LGTM

**Comment by arcbtc** [comment]
I think its nice to keep the short description once activated, and the "new version" badge seems a bit floaty

**Comment by blackcoffeexbt** [comment]
@dni I'd agree with @arcbtc on this. Keeping the short desc visible is important and the "new version" label should be positioned somewhere that it feels more "docked" to the card. Closer to a corner with a fixed distance would be good.

**Comment by arcbtc** [comment]
I like @dni chnages, looks waaaayyy better on mobile, but I think we should keep the short description

**Review by arcbtc — APPROVED** [review]

**Pull request merged**
