### PR TITLE
fix issue: #897, ugly memo in payments list

### PR DESCRIPTION
**Pull request by dni**
Fixes: #897

### CODE REVIEW

**Comment by dni** [comment]
screenshot-1660985475

memo is now a 1 liner

**Comment by dni** [comment]
another addition, don' t use columns for payment-details
### before
screenshot-1660987304

### after
screenshot-1660988731
screenshot-1660988722

i leave this pr as is, i think its subjectively better than before, but i do not want get into any design discussion :).

**Comment by arcbtc** [comment]
thats a long phone you have there!

**Comment by arcbtc** [comment]
Be good to get this merged, but it needs compacting for a smaller screen Add some `v-if="gt-md"`, or something similar to some padding elements to tuck it all in 👍.

**Pull request closed without merging**
