### PR TITLE
Cron task for running functions

### PR DESCRIPTION
**Pull request by arcbtc**
### A cron job type function:
The lnbits/task `timed_job(<funct>, <time>)` adds functions to a list indexed by time. When the `scheduled_tasks[<key>] == <time>` the functions in that key run.

Added a simple example for testing at `http://127.0.0.1:5000/api/v1/time`. 5secs after hitting, Loguru will print `Cron worked!
` 

https://user-images.githubusercontent.com/33088785/206215667-a6d889b9-4de0-4db7-8801-f2e931584064.mp4

### CODE REVIEW

**Comment by arcbtc** [comment]
I love this thing. You mentioned in a chat about coming up with a more sophisticated solution @callebtc ?

**Comment by callebtc** [comment]
This is cool, but I would've gone the object-oriented way and made a class, I think that's what I mentioned!

**Comment by arcbtc** [comment]
Maybe we could have a design sprint for this function in a few weeks, as I can imagine this fictionality being very useful for extension developers. I already have a few extension ideas, lotteries, push subscription services, etc, etc, etc, etc

**Comment by bitkarrot** [comment]
Would love to see this feature in LNBits. I'd love to issue recurring invoices, also would be helpful for the recurring payments ext that is an open PR

**Comment by arcbtc** [comment]
I want this merged in

**Comment by arcbtc** [comment]
Reopening, because this is cool, and everyone wants cron

**Comment by bitkarrot** [comment]
I dunno if it would be useful but maybe could borrow and merge in some of the code from https://github.com/bitkarrot/scheduler/, which you and @motorina0 requested last year?

my hands been kind of full recently and so i haven't been able to fully maintain it. @motorina0

**Comment by motorina0** [comment]
Yes, the `scheduler` extension should be where all the `cron` jobs are maintained.
Closing this PR.

One more approval required: https://github.com/lnbits/lnbits-extensions/pull/263

**Pull request closed without merging**
