### PR TITLE
Add option to add a background image and neon borders

### PR DESCRIPTION
**Pull request by arcbtc**
Part of the break up of https://github.com/lnbits/lnbits/pull/2817

Background images are blurred so smaller images can be used and also as most images scaled suck.
People love customising, and I'm sure users will have a lot of fun with this OPTIONAL feature.
(if you nack, you nack fun, are anti-choice and hate liberty and expression)

Next: after merge I will add to settings so an admin can set as global, so an admin can force their users to use their garish theme.

image
image
image

### CODE REVIEW

**Comment by BenGWeeks** [comment]
Ha ha, nice work. Look forward to seeing more.

**Comment by BenGWeeks** [comment]
Would love to see some pre-built extensive themes, such as "Cypherpunk".

**Comment by arcbtc** [comment]
> Would love to see some pre-built extensive themes, such as "Cypherpunk".


Nice idea, but it would get to messy. I cant wait to see what the people will make on there own

**Review by talvasconcelos — APPROVED** [review]

**Review by motorina0 — APPROVED** [review]
Hot!

Styling logic should be extracted in `ui-customisation.js`

**Pull request merged**
