### PR TITLE
Allow creation of invoices with msat precision

### PR DESCRIPTION
**Pull request by zebra-lucky**
Hi!

These changes allow create invoices with msat precision.
No gui changes, except allow wallet balance show fractional part of sats.
Intended for use via API calls.

### CODE REVIEW

**Comment by zebra-lucky** [comment]
Looking why regtest fails.

**Comment by zebra-lucky** [comment]
rebased on current `main`

**Comment by HamishMacEwan** [comment]
Given the many uncertainties even in sats denominated invoices (withholding thresholds, channel close reservations, etc, etc.) what is the benefit in permitting user specification of amounts as, currently admittedly, insignificant as millisats?

LNbits is not designed for either very large, or microscopically tiny, amounts.  It seems likely this will cause more trouble than it's worth.

**Comment by zebra-lucky** [comment]
Rebased on current `main`

**Pull request closed without merging**
