### PR TITLE
fix: properly fix check_funding_source

### PR DESCRIPTION
**Pull request by dni**
saas did not like that retrying loop at all :(

### CODE REVIEW

**Review by talvasconcelos — APPROVED** [review]

**Comment by motorina0** [comment]
NACK

**Review by motorina0 — CHANGES_REQUESTED** [review]
`max_retries` should be an env setting

**Comment by motorina0** [comment]
I would rather prefer this more flexible approach: https://github.com/lnbits/lnbits/pull/2404

**Comment by prusnak** [comment]
I like https://github.com/lnbits/lnbits/pull/2404 more than this approach

**Pull request closed without merging**
