### PR TITLE
Replace ISO codes with Flags

### PR DESCRIPTION
**Pull request by SuperAtic**

### CODE REVIEW

**Comment by callebtc** [comment]
\nACK on the flags. I like the letters better, less colors, visual clutter.

**Comment by arcbtc** [comment]
Im 55/45, 55 in favor of boring letters
What does rest of the world do?

**Comment by arcbtc** [comment]
the ui needs fixing as that list is getting long

**Comment by arcbtc** [comment]
Yep boring letters Im afraid, closing for now. they are less confusing, lots of color blind people using lnbits.
Thanks for contribution anyway, sorry this one didnt pass :(

**Comment by Bashy** [comment]
> Im 55/45, 55 in favor of boring letters What does rest of the world do?

Both?

**Pull request closed without merging**
