### PR TITLE
Stream Alerts extension

### PR DESCRIPTION
**Pull request by Fittiboy**
This will add the extension described in #225.
Will probably take me a while to implement, as this is my first time working with most of the tools used here.
I would greatly appreciate help with the front end, as I don't know JS at all.

### CODE REVIEW

**Comment by arcbtc** [comment]
I'll help! If you make the backend api working (copy/paste a good extension, edit accordingly), I'll get the frontend working for you

**Comment by Fittiboy** [comment]
Thanks for offering your help, and also thanks to @fiatjaf for offering help here: Fittiboy/bitcoin-on-twitch/issues/7
Feel free to do this whenever you're most comfortable dedicating your time to it. I'm in no rush, but I'll try to get the backend done asap :+1:

**Comment by Fittiboy** [comment]
I got a _bunch_ of stuff working in the backend now, but lots is still missing and quite some stuff only halfway done.
If anyone wants to check if there are already egregious mistakes I've made, style-wise for example, that would be cool. This is my first time really working with most of the libraries involved, so I expect the worst. :sweat_smile: 
I've decided to use SatsPayServer charges, which works out perfectly. I also already have a few extra features in mind that I'll add once there's a working MVP with a frontend.

**Comment by fiatjaf** [comment]
Please use lowercase names for everything except class declarations, otherwise the Python gods will strike us with lightning.

For example, `twitchalerts_ext`.

**Comment by Fittiboy** [comment]
Will do! So far I‘ve just been too lazy to change it, but I personally like snake_case most anyway.😅

**Comment by Fittiboy** [comment]
The API endpoints to:
1. Add a `Service` (so far only Streamlabs),
1. Authenticate with the corresponding third party API (obviously only Streamlabs here as well),
1. Create a `Donation`,
1. Post said `Donation` to the third party API once paid,

are done! I haven't added any documentation or helpful comments yet, but it should be simple-ish to follow the code to understand the flow.

The frontend should be rather simple:
* `twitchalerts/`: 
  * Essentially a copy of `lnticket/`, but replacing `Forms` and `Tickets` with `Services` and `Donations` respectively.
  * Next to the little button that links to each respective `Form` front end should be another button with the API authentication link for the respective `Service`, as well as a button for the redirect URI that Streamlabs needs.
  * I should be able to just copy and modify this from the Support Tickets extension myself, hopefully tomorrow.
* `twitchalerts/<service_state>/donate`:
  * Essentially a copy of `lnticket/<ID>`, but replacing the fields with `Name`, `Amount (sats)`, and `Message`.
  * Additionally, another field, `Amount (fiat)` with the amount converted (live, as the amount of sats changes) to any of the [supported currencies](https://streamlabs.readme.io/docs/currency-codes), selected from a drop down menu next to it.
    * Ideally, a user should also be able to enter the amount in fiat, which should update the `Amount (sats)` field correspondingly.
  * This, I likely won't be able to do by myself, because I don't think there is any place for me to copy the currency conversion fields from.

Before working on any of the frontend parts that I can copy -> paste -> modify, I will add comments to all of my code. If anyone wants to review it before I've added the comments, that would still be greatly appreciated of course!

**Comment by Fittiboy** [comment]
Surprisingly, I got a working frontend. It's full of bugs, but it does its job for now.
I will clean things up a bit before asking for help with the frontend, but if there are already any terrible mistakes I've made, please let me know!
If you want to test the extension yourself already, you can follow parts of [this guide](https://github.com/Fittiboy/bitcoin-on-twitch), and/or ask me for help.

**Comment by Fittiboy** [comment]
I have added comments, docstrings, and to generally cleaned things up a little.
The extension's general functionality is in place, thought the frontend is rudimentary and broken in some aspects:
 * When creating a service, the page has to be refreshed before it appears in the list
 * When editing a service, the form would keep resetting
   (I have removed the edit button for now)
 * The donation form has no currency conversion, and for now simply auto-converts to USD
 * There is no way to give the user the redirect URI they have to set in their Streamlabs application for authentication.
   crud.py _does_ have `get_service_redirect_uri(request, service_id)` available, which creates this URI based on the domain the extension is accessed from.

I will finish the README.md once everything else is finalized.
For now I'm essentially stuck, as my frontend knowledge¹ ends here. I have no experience building for web, so my code is likely not at all up to standards. If anyone can look at my current code and also fix the remaining frontend issues, that would be perfect.

¹ I tried to copy paste from other extensions

**Comment by arcbtc** [comment]
Does this work for anything using streamlabs, would it be better named "Streamlabs Alerts: bitcoin tips in you streamlabs feed!"

**Comment by Fittiboy** [comment]
I am planning on adding support for [StreamElements](https://dev.streamelements.com/docs/kappa/api.yaml/paths/~1tips~1%7Bchannel%7D/post), since those API docs recently popped up. Looks like they have enough info in there now for me to actually add support for it!

**Comment by arcbtc** [comment]
Ah yes, that makes sense. But it can be used for more than just twitch?

**Comment by arcbtc** [comment]
No, I see. dont worry

**Comment by arcbtc** [comment]
Any integration thats beyond windows?

**Comment by Fittiboy** [comment]
I know YouTube has their own "Super Chat" system for tips, but I would assume they‘d have to be allowed to accept tips through other services too. Don‘t know anything about Facebook Gaming, but both Streamlabs and StreamElements have option to log in through all three platforms. I‘ll try to look into that.

**Comment by Fittiboy** [comment]
> Any integration thats beyond windows?

What do you mean by this?

**Comment by arcbtc** [comment]
Looks like streamlabs/elements are windows only?

**Comment by Fittiboy** [comment]
Ah I see what you mean! Their alerts are just browser sources that you can throw into normal OBS Studio. There’s actually no need to use their proprietary software! I stream on Linux and use Streamlabs alerts myself.

**Comment by arcbtc** [comment]
Wow, cool

**Comment by arcbtc** [comment]
Can you please add instructions? I'm lost and the instructions go to a irrelevant guide

**Comment by Fittiboy** [comment]
I'll add a detailed guide asap. I probably don't have the time today and tomorrow, but if you're stuck on a specific step, I might be able to help you with that right now.

**Comment by Fittiboy** [comment]
Sorry for my long absence! I've now finished all the basic features and added a full guide to the README.md that should be straightforward to follow. From my point of view, the only thing blocking this from being ready to merge is the fact that after creating a service on index.html, the site has to be refreshed in order for the service to show up.
For now, I've just included this issue in the guide, telling the user to refresh the page, as I have absolutely no clue how to fix it. It's probably a simple fix, but I only know absolute basic HTML, and no JS at all. So if someone else could fix that bug, that would be sweet!

**Comment by Fittiboy** [comment]
Also, an update on the StreamElements situation: While they do have an API, it is not openly available at the moment, meaning that so far, the extension is limited to just Streamlabs.

**Pull request merged**
