### PR TITLE
feat: wallet name in payments export

### PR DESCRIPTION
**Pull request by jackstar12**
closes: #1984

### CODE REVIEW

**Review by dni — APPROVED** [review]

**Comment by dni** [comment]
what does this exportCSV do in wallet.js ?
https://github.com/lnbits/lnbits/blob/54e0d1aa15749f8b1916c454d1daea5a0e0f4bfc/lnbits/core/static/js/wallet.js#L807

**Review by dni — CHANGES_REQUESTED** [review]
can you check if exportCSV in `wallet.js` is also relevant?

**Comment by jackstar12** [comment]
> can you check if exportCSV in `wallet.js` is also relevant?

what do you mean? if it could be refactored?

**Comment by dni** [comment]
> > can you check if exportCSV in `wallet.js` is also relevant?
> 
> what do you mean? if it could be refactored?

the wallet name in this export should also be present, right?

**Review by dni — APPROVED** [review]
my bad, :D i confused myself

**Review by prusnak — APPROVED** [review]

**Comment by prusnak** [comment]
Tested and merged! Thanks

**Pull request merged**
