### PR TITLE
feat: Blink Funding Source - GraphQL API integration

### PR DESCRIPTION
**Pull request by bitkarrot**
Blink Wallet API Integration - WIP

Note: the test script is not in proper pytest format, will convert after I get the main part working. 

Referencing https://github.com/lnbits/lnbits/issues/2227

### CODE REVIEW

**Comment by bitkarrot** [comment]
Note Please don't edit this branch until it is ready for review. thanks.

**Comment by bitkarrot** [comment]
Waiting for Galoy/Blink Devs to write in a new method to their GraphQL endpoint in order to complete this integration.
Will take a few days.

cc: @openoms

**Comment by bitkarrot** [comment]
Not sure if this is the right way to do the unit test, but I tried as a first pass. 

Also graphql is really long seems to break the formatter.

**Comment by bitkarrot** [comment]
If someone can please run and test, that'd be appreciated. 

cc: @openoms, @pretyflaco

**Comment by bitkarrot** [comment]
I will fix the conflicts in the am...

**Comment by openoms** [comment]
Thank you for this great PR @bitkarrot, it looks very close to completion!

Been setting up server running this branch and tested successfully:
- [x] adding a Blink API key and switching funding source
- [x] send over LN
- [x] receive over LN
- [x] send intraledger (Blink to Blink)
- [x] receive intraledger

Extensions tried:
- [x] LNURLw vouchers works
- [x]  Bolt card works
- [x] TPoS works

One thing I noticed so far that if I just simply top up a wallet with the RECEIVE button on the bottom left the payment does not get picked up live. Need to close the invoice and refresh the screen to see the balance change.

Tested this with switching the funded source to another LNbits and on another instance backed by CLN - there the payment is picked up live. 

Note the TPOS is getting the instant feedback with the green checkmark.

Could this be solved?

Please anyone else testing, this is the best time for any feedback.

**Comment by bitkarrot** [comment]
@openoms i'm looking into how we can get the websocket part going for the receive issue.

**Comment by bitkarrot** [comment]
putting websocket method on hold. 

requesting review from @prusnak  and @dni when possible. 

cc: @openoms

**Comment by bitkarrot** [comment]
Updated branch to resolve conflicts and make format. 

CI is failing on i18n files, appears unrelated to branch

**Comment by prusnak** [comment]
I rebased and squashed this PR into a new PR https://github.com/lnbits/lnbits/pull/2477

I suggest we continue there

**Pull request closed without merging**
