### PR TITLE
 add python-crontab for scheduler extension

### PR DESCRIPTION
**Pull request by bitkarrot**
- see pyproject.toml for the dependency addition, and comment by @motorina0 here: https://github.com/bitkarrot/scheduler/issues/8#issuecomment-1754662019

### CODE REVIEW

**Comment by prusnak** [comment]
you need to also run `poetry lock --no-update` so `poetry.lock` file is refreshed

**Review by prusnak — CHANGES_REQUESTED** [review]
you need to also run poetry lock --no-update so poetry.lock file is refreshed

**Comment by bitkarrot** [comment]
> you need to also run `poetry lock --no-update` so `poetry.lock` file is refreshed

OK I ran the above and checked in the poetry.lock file. Let me know if its correct or not.

**Comment by prusnak** [comment]
@bitkarrot you are running old version of poetry (1.4.2) while the poetry lock has been generated with a newer one (1.5.1). The older version added lot of unneeded stuff, so I rerun the `poetry lock --no-update` with a newer version and replaced the last commit in your PR branch.

**Review by prusnak — APPROVED** [review]

**Comment by bitkarrot** [comment]
Ok whoops I will update my poetry now. It auto updated to 1.6.1 

Thanks for updating the file. @prusnak

**Review by motorina0 — APPROVED** [review]

**Review by dni — APPROVED** [review]

**Pull request merged**
