### PR TITLE
bug: Fix regression. Admin-users and allowed-users can now be removed through the web interface

### PR DESCRIPTION
**Pull request by dethos**
In the server administration, more precisely on the “Users” tab, `admin-users` and `allowed-users` cannot be removed. This was originally reported on https://github.com/lnbits/lnbits/issues/2297.

After a quick search through recent commits, the problem seems to have been created as part of a recent PR (https://github.com/lnbits/lnbits/pull/2252). 

This PR reverts some of those changes, in order for this functionality to work again.

### CODE REVIEW

**Comment by dni** [comment]
can you allow upstream maintainers to push to this branch? i would have fixed it differently. if you give me permission i can push and maybe you can help me test. or try it yourself

```
          <q-chip
            v-for="user in formData.lnbits_admin_users"
            :key="user"
            removable
            @remove="removeAdminUser(user)"
            color="primary"
            text-color="white"
          >
            <span v-text="user"></span>
          </q-chip>

```

**Review by dni — CHANGES_REQUESTED** [review]
above

**Comment by dethos** [comment]
> thanks for you contribution!
> 
> can you allow upstream maintainers to push to your branch? i would have fixed it differently. if you give me permission i can push and maybe you can help me test. or try it yourself. instead of reintroducing `{{ raw ]}` try using the v-text on a span, we did it like that on the q-tooltip element aswell.
> 
> ```
>           <q-chip
>             v-for="user in formData.lnbits_admin_users"
>             :key="user"
>             removable
>             @remove="removeAdminUser(user)"
>             color="primary"
>             text-color="white"
>           >
>             <span v-text="user"></span>
>           </q-chip>
> ```

@dni Fixed. Manually tested and it works as expected.

**Review by dni — APPROVED** [review]
LGTM! thank you

**Review by prusnak — APPROVED** [review]

**Review by talvasconcelos — APPROVED** [review]

**Pull request merged**
