### PR TITLE
feat: add boltz client fundingsource

### PR DESCRIPTION
**Pull request by dni**
https://docs.boltz.exchange/v/boltz-client

this fundingsource utilizing the boltz client standalone function: https://github.com/BoltzExchange/boltz-client/pull/123 this makes him act like a lightning node while submarine swapping everything on liquid network. like aqua does in its wallet. its basically a liquid wallet.

live mainnet instance: https://boltz.dni.guru/

### CODE REVIEW

**Comment by arcbtc** [comment]
Poor rebase on my part, was trying to help, sorry!

**Comment by dni** [comment]
> Poor rebase on my part, was trying to help, sorry!

fixed it

**Review by prusnak — APPROVED** [review]
utACK

**Comment by prusnak** [comment]
You might want to add Boltz logo to the main index like we do with all funding sources. But it's not a blocker for this PR

**Comment by dni** [comment]
> You might want to add Boltz logo to the main index like we do with all funding sources. But it's not a blocker for this PR

done, thanks!

**Comment by prusnak** [comment]
The last commit replaces NWC logo with Boltz instead of adding it.

**Comment by dni** [comment]
nwc logo is missing, you cant see the link, thats why i removed it

**Comment by prusnak** [comment]
> nwc logo is missing, you cant see the link, thats why i removed it

ok, let's fix the missing NWC logo in subsequent PR

**Review by prusnak — APPROVED** [review]

**Review by prusnak — APPROVED** [review]

**Review by arcbtc — APPROVED** [review]

**Pull request merged**
