### PR TITLE
Boltcard ext upgrade

### PR DESCRIPTION
**Pull request by iWarpBTC**
- updated readme (also responsing to issue #949)

- added webhook for notifications

### CODE REVIEW

**Comment by arcbtc** [comment]
I wonder if it makes sense to add a webhook option to `pay_invoice` in `core.services` then this extension and any other could make use of it?

**Comment by iWarpBTC** [comment]
I believe that's a good idea. Could it look like something like in last commit?

**Comment by iWarpBTC** [comment]
> I wonder if it makes sense to add a webhook option to `pay_invoice` in `core.services` then this extension, and any other, could make use of it?

I believe that's a good idea. Could it look like something like in the last commit?

**Comment by iWarpBTC** [comment]
It should be ready for a review. I'm wondering what you say to passing the webhook either as a string or as a tuple. Wouldn't be better to just split it to two params?

**Comment by iWarpBTC** [comment]
I've just reduced this PR which I had let to grown in a nasty way. 

Remain
-  the ability to wipe a card with Boltcard NFC Card Creator (since v0.1.2)
-  revised card delete flow (with force downloading keys in a wipe json)
-  reason of payment fail is returned to a charging service
-  some import clean up
-  readme update. 

I keep the webhook updates for another PR. 

Hope this help to move this forward.

**Pull request merged**
