### PR TITLE
fix sys is not defined

### PR DESCRIPTION
**Pull request by ChuckNorrison**

### CODE REVIEW

**Comment by motorina0** [comment]
For consistency across the app we should use the approach at `lnbits/app.py`:

```py
import sys
...
sys.exit(1)
```

**Comment by motorina0** [comment]
Merging: failed checks unrelated to this PR.

**Comment by motorina0** [comment]
Looks good, please format and I will merge.
Thank you for the fix!

**Comment by ChuckNorrison** [comment]
> Looks good, please format and I will merge. Thank you for the fix!

i dont understand what format is wrong

**Comment by motorina0** [comment]
Merging: 
 - the `regtest` check failures are unrelated to this PR
 - will fix formatting in a different PR

**Pull request merged**
