### PR TITLE
add i18n checker

### PR DESCRIPTION
**Pull request by prusnak**
As discussed in https://github.com/lnbits/lnbits/issues/2122, I came up with an i18n checker scripts. As we can see from running it, there are many unmaintained language files with lots of missing and unused strings.

```
$ python3 tools/i18n-check.py | grep Missing
Missing ids in language "br": 95
Missing ids in language "cn": 64
Missing ids in language "de": 70
Missing ids in language "es": 70
Missing ids in language "fr": 95
Missing ids in language "it": 95
Missing ids in language "jp": 71
Missing ids in language "kr": 2
Missing ids in language "nl": 95
Missing ids in language "pi": 95
Missing ids in language "pl": 95
Missing ids in language "pt": 95
Missing ids in language "we": 95
```

### CODE REVIEW

**Comment by dni** [comment]
awesome stuff :+1:

**Comment by dni** [comment]
wow! can you put that code inside the checker :D that would be awesome for future label to be translated via script

**Comment by prusnak** [comment]
> wow! can you put that code inside the checker :D that would be awesome for future label to be translated via script

Currently it is pretty rough. I plan to polish it first and push it soon via another PR.

**Comment by prusnak** [comment]
Superseded by https://github.com/lnbits/lnbits/pull/2160

**Pull request closed without merging**
