### PR TITLE
Fix overlapping redirect paths

### PR DESCRIPTION
**Pull request by motorina0**
### Summary
Derived from: https://github.com/lnbits/lnbits/issues/2540
If two extensions (`ext_a` and `ext_b`) have overlapping redirect paths then the second one (`ext_b`) will be installed but deactivated.
If `ext_a` is deactivated, then `ext_b` can be activated.
See test scenario here:
image

The PR with JMeter tests: https://github.com/lnbits/lnbits-extensions/pull/415

This PR extended a bit outside the scope defined in the title. Some of the concepts in extension manager got clearer and I've decide to also refactor the extension manager and add tests to guard for future bugs.

### Changes
Short explanation of the relevant changes per file:
- `app.py` (refactor)
  - extract redirect logic from this file to `settings.activate_extension_paths`

- `commands.py` (refactor)
  - update function calls and imports
- `crud.py` (code quality only)
- `extension_manager.py`
    - moved to the `core/extensions` directory
    - all the classes have been moved to `extensions/models.py`
    - utilities have been moved to `extensions/helpers.py`
    - it contains only the logic for install/uninstall, activate/deactivate and stop_background_work
      - `stop_extension_background_work` changes:
        - do not call via API anymore (all extensions have `_start` & `_stop` now)
        - fix `stop_fn()` in case it is not an `async` function
 - `extensions/helpers.py`
   -  helpers extracted from the `extension_manager.py` (no new logic)
 - `extensions/models.py`
   - classes extracted from  `extension_manager.py` (no new logic, some standalone functions are now `@classmethods`)
- `extensions_api.py` (extract some methods and update imports) 
- `middleware.py` (simplify, extract path logic to its own `RedirectPath` class)
- `settings.py`
  - encapsulate the path redirect logic here instead of having it in multiple places in the app
  - fix bug for update extension
- `test_settings.py` (add tests for the `RedirectPath` class)

### CODE REVIEW

**Comment by prusnak** [comment]
Can you describe in words how do you fix the issue?

What happens if two extensions register the same path?

**Comment by motorina0** [comment]
> Can you describe in words how do you fix the issue?
> 
> What happens if two extensions register the same path?

OMG @prusnak you're like the `eye of sauron`, but with good intentions :)

The plan is simple: 
  - do not allow the second extension to be installed if there is a conflict
  - inform the admin user about the nature of the conflict and the name of the other extension that it conflicts with
  - similar with two apps listening on the same port

**Comment by motorina0** [comment]
> The plan is simple:
> 
>     * do not allow the second extension to be installed if there is a conflict
> 
>     * inform the admin user about the nature of the conflict and the name of the other extension that it conflicts with
> 
>     * similar with two apps listening on the same port

More details and final decision once the PR is out of draft.

**Comment by prusnak** [comment]
> OMG @prusnak you're like the `eye of sauron`, but with good intentions :)

sorry, I don't want to be a pain in the ass, I was just very curious how to solve this particular issue since I first stumbled upon it for the first time a few weeks ago :

**Review by arcbtc — APPROVED** [review]

**Pull request merged**
