### PR TITLE
chore: update pyproject dependencies

### PR DESCRIPTION
**Pull request by prusnak**
i did not touch sqlalchemy since this is being worked on here: https://github.com/lnbits/lnbits/pull/2611

### CODE REVIEW

**Comment by prusnak** [comment]
this PR is now ready

jmeter fails but this is unrelated to the PR imho

**Review by dni — APPROVED** [review]
maybe bump lnurl once more just did a fix and release. https://github.com/lnbits/lnurl/releases/tag/v0.5.2

**Comment by prusnak** [comment]
> maybe bump lnurl once more just did a fix and release. https://github.com/lnbits/lnurl/releases/tag/v0.5.2

done

**Comment by prusnak** [comment]
withdraw extension failure reported here: https://github.com/lnbits/withdraw/issues/47

**Comment by prusnak** [comment]
> withdraw extension failure reported here: [lnbits/withdraw#47](https://github.com/lnbits/withdraw/issues/47)

fix for withdraw extension here: https://github.com/lnbits/withdraw/pull/48

**Review by motorina0 — APPROVED** [review]

**Review by talvasconcelos — APPROVED** [review]

**Pull request merged**
